CREATE SEQUENCE MISSAO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_ESG_MISSAO (
    ID_MISSAO INTEGER DEFAULT MISSAO_SEQ.NEXTVAL PRIMARY KEY,
    NOME VARCHAR2(255) NOT NULL,
    DESCRICAO VARCHAR2(1000),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    PONTOS_BASE NUMBER,
    TIPO_MATERIAL VARCHAR2(255)
);
