ALTER TABLE T_ESG_REGISTRO_ATIVIDADE
DROP CONSTRAINT FK_REGISTRO_MISSAO;

ALTER TABLE T_ESG_REGISTRO_ATIVIDADE
ADD CONSTRAINT FK_REGISTRO_MISSAO
FOREIGN KEY (T_ESG_MISSAO_ID_MISSAO)
REFERENCES T_ESG_MISSAO(ID_MISSAO)
ON DELETE CASCADE;
